name: Deploy Firestore Rules

on:
  push:
    branches:
      - main
    paths:
      - 'firestore.rules'
      - '.github/workflows/deploy-rules.yml'

jobs:
  deploy_rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Firestore Rules
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore:rules
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ANGESCOMPANY_SOULROOM }}
          PROJECT_ID: soulroom-74c97
